### ISSUE TITLE
Auto Rename Variables

### ISSUE THREAD

**Issue by BryanFrederickson** [BryanFrederickson/CYBER1-CodeVersion#17]
**As a** developer,
**I need** to be able to modify variable names with synonyms of the original variable name by traversing a concrete syntax tree,
**So that** a semantic clone can look structurally different than it's seed source code.

### Details and Assumptions
* CST must be set up for traversing the program node types
*  Program can be rebuilt with the new changes

### Acceptance Criteria
```gherkin
Given that I want to generate clones from a seed Python file,
When I enter the program into the file accept box,
Then the output file contains changes in variable names that are closely related to the original variable names.
```

**Comment by KleinMandolin** [comment]
Closed as of most recent commits for main and python-notebook-tests branches. Variable renaming is fully covered with a backup animals wordbank if Gemini synonym requests fail.
